# Generated by Django 3.2.9 on 2021-11-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('isbn_num', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('libraries_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library_books',
            fields=[
                ('library_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_library_activity_id', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.books')),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.libraries')),
            ],
        ),
        migrations.CreateModel(
            name='Library_activites',
            fields=[
                ('library_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('out', 'Out'), ('in', 'In')], max_length=10)),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.users')),
            ],
        ),
    ]
