# Generated by Django 3.2.9 on 2021-11-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_activites',
            name='library_book_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.library_books'),
        ),
    ]
