# Generated by Django 3.2.9 on 2021-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_library_activites_library_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_books',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='library_id',
            field=models.IntegerField(),
        ),
    ]
