# Generated by Django 3.2.9 on 2021-11-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_auto_20211128_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_books',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.books'),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='library_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.libraries'),
        ),
    ]
