# Generated by Django 3.2.9 on 2021-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0006_auto_20211128_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraries',
            name='libraries_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='library_activites',
            name='checked_in_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='library_activites',
            name='checked_out_at',
            field=models.DateTimeField(),
        ),
    ]
