# Generated by Django 3.2.9 on 2021-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0009_alter_library_activites_checked_out_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_activites',
            name='checked_in_at',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='library_activites',
            name='checked_out_at',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
