# Generated by Django 3.2.9 on 2021-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0010_auto_20211128_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_activites',
            name='checked_in_at',
            field=models.TextField(default='0000-00-00', max_length=20),
        ),
        migrations.AlterField(
            model_name='library_activites',
            name='checked_out_at',
            field=models.TextField(default='0000-00-00', max_length=20),
        ),
    ]
